[package]
name = "report-generator"
version = "2.0.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.34", default-features = false, features = ["clock"] }
pico-args-helpgen = { git = "https://github.com/Ernest1338/pico-args-helpgen" }
